---
- hosts: localhost
  
  roles:
    - name: Install Docker
      role: geerlingguy.docker

    - name: Install Go
      role: geerlingguy.go

  vars:
    docker_users:
      - "{{ ansible_user_id }}"
    docker_compose_version: "v2.18.0"
    go_version: "1.19.2"

  tasks:
    - name: Setup environment
      import_tasks: tasks/setup_environment.yaml

    - name: Install Programming Tools
      import_tasks: tasks/install_programming_tools.yaml

    - name: Install zsh and oh-my-zsh
      import_tasks: tasks/install_ohmyzsh.yaml

    - name: Install Visual Studio Code
      import_tasks: tasks/install_vscode.yaml

    - name: Install tools
      import_tasks: tasks/install_tools.yaml
