---
- name: Import PGP key
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Check update
  ansible.builtin.dnf:
    update_cache: true

- name: Install Visual Studio Code
  ansible.builtin.dnf:
    name: code
    state: present
  become: true
