---
- name: Install gcc-c++
  ansible.builtin.dnf:
    name: gcc-c++
    state: present
  become: true

- name: Install cmake
  ansible.builtin.dnf:
    name: cmake
    state: present
  become: true

- name: Install Rust and its toolchain
  ansible.builtin.command: "curl https://sh.rustup.rs -sSf | sh"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/rustup"
